POST http://localhost:2700/api/users/createAccount HTTP/1.1
content-type: application/json

{
    "username": "DanLuk",
    "password": "Aaaaa"
}

###

POST http://localhost:2700/api/editList HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjcwNDM5NzgwLCJleHAiOjE2NzMwMzE3ODB9.9_ZCM7-Kyta9F-BpbGL71EntO0YXrK0RX5umEVOkWs8
content-type: application/json

{
    "remove": [
        {
            "id": 1611,
            "finishedAmount": 160,
            "status": "Planning"
        }
    ]
}

###

POST http://localhost:2700/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "DanLuk",
    "password": "Aaaaa"
}